### ISSUE TITLE
skip_ssl_verification option for git repos

### ISSUE THREAD

**Issue by mehrotra-prateek** [concourse/pool-resource#24] opened 2017-02-22 09:11 UTC
Hello,

Is there an option to use `skip-ssl-verification` option with the resource? I am trying to access a git server with a private certificate and have the need to use the option since ssh is disabled on this instance. 

Looking at the git resource code this could be an easy fix to include functions from git resource `https://github.com/concourse/git-resource/blob/d86bd0a8e7da75650ee4e0a08d6af28746754ffb/assets/common.sh#L31`

I am happy to do a pull request around this if its acceptable.

**Comment by chendrix** [comment] 2017-05-23 23:12
Closing as dupe of concourse/concourse#1027

**Closed by chendrix** 2017-05-23 23:12 UTC
